# Generated by Django 4.2.7 on 2024-02-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Luxury', 'Luxury')], max_length=100),
        ),
    ]
